# builder stage
FROM node:14 AS builder

WORKDIR /usr
COPY package.json ./
COPY tsconfig.json ./
COPY src ./src
RUN npm install typescript -g
RUN npm install
RUN npm run build

# Deploy stage
FROM node:14-alpine3.13

WORKDIR /usr
COPY package.json ./
COPY ecosystem.config.js ./
COPY .env ./
RUN npm install --only=production
COPY --from=builder /usr/dist .
RUN npm install pm2 -g
CMD ["npm", "start"]
